# Generated by Django 5.0.4 on 2024-06-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_measurement_measurement_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='pulse',
            new_name='HR',
        ),
    ]
