# Generated by Django 5.0.4 on 2024-06-18 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_measurement_hr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='database.patient'),
        ),
    ]
