# Generated by Django 5.0.4 on 2024-06-19 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_sensor_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='HR',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='patient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='database.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='saturation',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
